### ISSUE TITLE
Station ID not saving

### ISSUE THREAD

**Issue by nickdos** [safepay/rainmachine-willyweather#1]
I've installed the python script and registered an API key. I've tested my API key works with a few GET requests to https://api.willyweather.com.au/v2 and can see my key is working.

When I try to save a station ID, it appears to save but if I click "close" and then go back into the custom screen, the value is empty again. See 

<img width="1294" alt="RainMachine_Web_Application" src="https://user-images.githubusercontent.com/532845/63849399-569f2c80-c9d5-11e9-9612-74e925c956f8.png">

On the weather service list, it has a red warning "Retrying: URL open fail" that has been there since I first entered my key. I think my key was not activated then but it is now and that message persists.

I've tried a few of the suggested station IDs but none of them "stick". I've tried saving, then clicking refresh and a few other combinations of saving, closing, refresh, refreshAll, etc. 

Am I missing some step?

**Comment by nickdos** [comment]
I tried again with the mobile app (iOS) and it successfully saved the station ID, so maybe its an issue with the web interface (I was using Safari version 12.1.2 on Mac OS X 10.14.6).

**Comment by aussieEd** [comment]
Unfortunately, I am experiencing the same issue and trying to add the station ID via the app did not resolve the issue and the station id field is simply cleared on save. I have tried several browsers and platforms (Mac, Windows, iOS App, Chrome, Safari) and have not had any luck. 

Any advice much appreciated!

Ed.

**Comment by safepay** [comment]
RM seems to have trouble saving the data. The parser has no control over that process. All it does is name the variables.

My advice is to use the Defaults option. Then save. Then try setting the station id again. 

You may need to try this a few times to get it to work. 

There is nothing I can do about this unfortunately.

**Comment by safepay** [comment]
I've created a separate Troubleshooting section in the README to make the fix for this more prominant.
