### ISSUE TITLE
Rainmachine8 unable to load willyweather.txt in Win10

### ISSUE THREAD

**Issue by EBPC** [safepay/rainmachine-willyweather#2]
Hi, I feel I have everything right following your excellent guide, but RM8 fails to load the willyweather.txt file in Win 10. The firmware is 4.0.999 which is the current version. Any ideas what might be wrong? I've tried loading from a Macbook both the .py and .txt and they both fail also. I appreciate that you may not have time/inclination to help which is fine, but maybe there has been a firmware change since this was written, if so I can stop trying to get this to work!

Regards Collin

**Comment by safepay** [comment]
Hi.

As I put in the readme, it is very difficult to get these files loaded onto RainMachine on anything other than Linux.

You have to have the .py extension or it won't work at all.

This is a caveat with RainMachine, not the plugin unfortunately.

I don't have a Mac, but I do have Linux machines, which is how I get it to work.

**Comment by EBPC** [comment]
Hi Richard, Many many thanks for your very speedy reply. I'll have to get myself a Linux distro and see if I can get my PC to boot into into and wrestle with Linux for a bit. It's all good learning; I did try Linux a long time ago in one of my many fed up with Microsoft moments, but at the time getting drivers to work was the issue.
Keep well out in bush, Collin

**Comment by EBPC** [comment]
Hi Richard, I've downloaded and run Ubuntu 19.1 Desktop and things have certainly improved since I last ran Linux. However I still can't get willyweather.py to load. I wonder if you could tell me, is your Rainmachine an Mini 8, a Pro  or Touch HD and which firmware does it run? I can't think of any other obvious reason for it not to work except I'm running a Desktop and not a loaded full version perhaps. Any ideas?
Many thanks, Collin

**Comment by safepay** [comment]
Hi Collin,

Mines in an HD12 running firmware 4.0.1129 

I would suggest posting this in the RainMachine formums as more people may be able to assist with this kind of troubleshooting.

E.g. https://support.rainmachine.com/hc/en-us/community/posts/360012942414-Custom-User-Uploaded-Weather-Service-and-Reboots

For me, I just upload via Firefox on Ubuntu and it works fine.

**Comment by EBPC** [comment]
Hi Richard, Thank you for the advice - I'll post on the Rainmachine forum. We have different units and my firmware is newer than yours so it may not work on mine. If I get it to work I'll let you know in case somebody else bothers you!

**Comment by safepay** [comment]
Closing as this is not a parser issue and has been dealt with in RM forum.
