### ISSUE TITLE
Weather is a day ahead in Rainmachine

### ISSUE THREAD

**Issue by lawnbook** [safepay/rainmachine-willyweather#3]
Thanks for setting this up, do you have any idea why the weather is showing a day ahead of what it should be, my time zone and date/time as all set correct

![image](https://user-images.githubusercontent.com/90117575/133603817-4ee44e75-2002-4cb6-8080-724f1be81fe4.png)

**Comment by safepay** [comment]
Thanks for that. I've been running this for a long time and it always shows the right weather on the right day, so not sure what the problemon your system is.
